// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.TaskAPI;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(PreAdviceDbContext))]
    [Migration("20240514085958_task")]
    partial class task
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.TaskAPI.PreAdvice", b =>
                {
                    b.Property<int>("preAdviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("preAdviceId"));

                    b.Property<string>("depot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("liner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("redelAuthDate")
                        .HasColumnType("date");

                    b.Property<string>("redelAuthNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vesselCarrier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vesselName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("preAdviceId");

                    b.ToTable("PreAdvices");
                });
#pragma warning restore 612, 618
        }
    }
}
